version: "2"

services:
  app:
    image: "node:14"
    user: "node"
    stdin_open: true
    tty: true
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - PORT=${PORT}
    volumes:
     - ../../../scripts:/home/node/scripts
     - ../.:/home/node/app
     - ../../common:/home/node/app/src/common
    expose:
      - "${PORT}"
    ports:
      - "${PORT}:${PORT}"
    command: "sh /home/node/scripts/entrypoints/${ACTION}.sh"
  redis:
    image: "redis:6"
